FROM python:3.12-slim as base

WORKDIR /app

RUN apt-get update \
&& apt-get install -y build-essential curl software-properties-common git \
&& apt-get clean \
&& pip3 install --no-cache-dir -U pip \
&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

RUN mkdir -p /app/logs

COPY . .

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD curl --fail http://localhost:80/_stcore/health

ENTRYPOINT ["python3", "-m", "streamlit", "run", "admin_dashboard/Home.py", "--server.port", "8080"]
