"""Add on delete cascade to user

Revision ID: 3f1244fca49e
Revises: 74c73b578a2f
Create Date: 2024-04-21 16:34:01.524860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1244fca49e'
down_revision: Union[str, None] = '74c73b578a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('matchmaking_counter_user_id_fkey', 'matchmaking_counter', type_='foreignkey')
    op.create_foreign_key(None, 'matchmaking_counter', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('matchmaking_results_user_id_fkey', 'matchmaking_results', type_='foreignkey')
    op.create_foreign_key(None, 'matchmaking_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('matchmaking_user_rating_user_id_fkey', 'matchmaking_user_rating', type_='foreignkey')
    op.create_foreign_key(None, 'matchmaking_user_rating', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('participants_user_id_fkey', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('questions_asked_user_id_fkey', 'questions_asked', type_='foreignkey')
    op.create_foreign_key(None, 'questions_asked', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_profiles_user_id_fkey', 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key('user_profiles_user_id_fkey', 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'questions_asked', type_='foreignkey')
    op.create_foreign_key('questions_asked_user_id_fkey', 'questions_asked', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_user_id_fkey', 'participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'matchmaking_user_rating', type_='foreignkey')
    op.create_foreign_key('matchmaking_user_rating_user_id_fkey', 'matchmaking_user_rating', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'matchmaking_results', type_='foreignkey')
    op.create_foreign_key('matchmaking_results_user_id_fkey', 'matchmaking_results', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'matchmaking_counter', type_='foreignkey')
    op.create_foreign_key('matchmaking_counter_user_id_fkey', 'matchmaking_counter', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
