"""adding user rating model

Revision ID: 74c73b578a2f
Revises: 7e8b986ca640
Create Date: 2024-04-13 22:19:26.269096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c73b578a2f'
down_revision: Union[str, None] = '7e8b986ca640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchmaking_user_rating',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('candidate_user_id', sa.UUID(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchmaking_user_rating_id'), 'matchmaking_user_rating', ['id'], unique=True)
    op.add_column('matchmaking_results', sa.Column('candidate_user_id', sa.UUID(), nullable=True))
    op.alter_column('matchmaking_results', 'system_prompt_type',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matchmaking_results', 'system_prompt_type',
               existing_type=sa.INTEGER())
    op.drop_column('matchmaking_results', 'candidate_user_id')
    op.drop_index(op.f('ix_matchmaking_user_rating_id'), table_name='matchmaking_user_rating')
    op.drop_table('matchmaking_user_rating')
    # ### end Alembic commands ###
