"""Add on delete cascade

Revision ID: eccafef95a24
Revises: 3f1244fca49e
Create Date: 2024-04-21 16:57:33.701158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eccafef95a24'
down_revision: Union[str, None] = '3f1244fca49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_participant_association_conversation_id_fkey', 'conversation_participant_association', type_='foreignkey')
    op.drop_constraint('conversation_participant_association_participant_id_fkey', 'conversation_participant_association', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participant_association', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_participant_association', 'participants', ['participant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_participant_association', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participant_association', type_='foreignkey')
    op.create_foreign_key('conversation_participant_association_participant_id_fkey', 'conversation_participant_association', 'participants', ['participant_id'], ['id'])
    op.create_foreign_key('conversation_participant_association_conversation_id_fkey', 'conversation_participant_association', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
